# Generated by Django 3.2.6 on 2021-08-17 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_currency', models.CharField(help_text='Идентификатор валюты', max_length=7)),
                ('name', models.CharField(help_text='Название валюты', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nominal', models.IntegerField(help_text='Номинал валюты для курса')),
                ('date', models.DateField(help_text='Дата курса валюты')),
                ('value', models.DecimalField(decimal_places=4, help_text='Курс валюты', max_digits=10)),
                ('id_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbr_rates.currency')),
            ],
            options={
                'ordering': ['-date', 'id_currency'],
            },
        ),
    ]
